name: Bug Report
description: File a bug report
title: 'Bug: '
labels: ['bug']
projects: []
assignees:
  - Exponential-Workload
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give a detailed explanation of what happened.
      placeholder: Something died.
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: "What should've happened?"
      description: What did you expect to happen?
      placeholder: Everything to work!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce this?
      description: Provide a detailed explation of how to reproduce this.
      placeholder: |
        1. Open Cinny Desktop
        2. See Updater
        3. Click Update
        4. Nothing Opens
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Cinny Desktop are you running?
      options:
        - 1.0.x
        - Source (master)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - MacOS (currently unsupported)
  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: "If you're on a Linux distribution, which one? What version? When did you last update?"
      placeholder: ex. Arch (2023.12.25), Debian (Buster, 2023.12.25)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (this is public)
      placeholder: ex. expo@expo.moe
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      description: "By submitting this issue, you've checked that you cannot reproduce this issue on Cinny Web, on it's master branch - and can only reproduce it within cinny desktop."
      options:
        - label: "I've checked that I cannot reproduce this bug on Cinny's latest `master` commit with a standard browser."
          required: true
        - label: "I've checked that all of the above information is accurate."
          required: true
