name: Build Cinny
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-cinny:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Clone Cinny
        run: git clone https://github.com/cinnyapp/cinny.git .
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: pnpm build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: cinny-build
