name: Build PR
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-cinny:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Clone Cinny
        run: git clone https://github.com/cinnyapp/cinny.git .
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: cinny-build
  build-ubunut:
    runs-on: ubuntu-latest
    needs: [build-cinny]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Cinny
        uses: actions/download-artifact@v3
        with:
          name: build-ubunut
          path: ./.cinny
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          path: out
          name: build-ubunut
  build-wombat:
    runs-on: windows-latest
    needs: [build-cinny]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Cinny
        uses: actions/download-artifact@v3
        with:
          name: build-ubunut
          path: ./.cinny
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          path: out
          name: build-binbows
  build-marcos:
    runs-on: macos-latest
    needs: [build-cinny]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Cinny
        uses: actions/download-artifact@v3
        with:
          name: build-ubunut
          path: ./.cinny
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          path: out
          name: build-sackos
