name: Release

on:
  workflow_dispatch:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build-os:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    needs: [build-os]
    steps:
      - name: Install zip
        run: sudo apt install zip -y;
      - name: Download Ubunut
        uses: actions/download-artifact@v3
        with:
          name: build-ubunut
          path: ./bin/linux
      - name: Download Michaelsoft Binbows
        uses: actions/download-artifact@v3
        with:
          name: build-binbows
          path: ./bin/windows
      - name: Make output dir
        run: mkdir out
      - name: Tar Linux Plain
        run: cd bin/linux/Cinny\ Desktop-linux-x64; tar -czvf ../../../out/linux-bin-x64.tar.gz .;
      - name: Zip Linux Plain
        run: mv bin/linux/make/zip/linux/x64/Cinny\ Desktop-linux-x64-*.zip ./out/linux-bin-x64.zip;
      - name: Deb
        run: mv bin/linux/make/deb/x64/cinny-desktop_*_amd64.deb ./out/debian-x64.deb;
      - name: Zip Windows Plain
        run: cd bin/windows/Cinny\ Desktop-win32-x64; zip -r ../../../out/windows-bin-x64.zip .;
      - name: Squirrel exe
        run: mv bin/windows/make/squirrel.windows/x64/Cinny\ Desktop-*\ Setup.exe ./out/windows-setup-x64.exe;
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/linux-bin-x64.tar.gz
            out/linux-bin-x64.zip
            out/debian-x64.deb
            out/windows-bin-x64.zip
            out/windows-setup-x64.exe
